### PR TITLE
Implement sanitize.less

### PR DESCRIPTION
**Pull request by sotayamashita**
I have created less port and here is [codepen link](http://codepen.io/sotayamashita/pen/NxBQvV)

### CODE REVIEW

**Comment by jonathantneal** [comment]
@sotayamashita, thanks for putting this together. The CodePen is not fully loading for me, and testing the CSS in [less-preview](http://lesscss.org/less-preview/) gives me errors.

Also, is there any way to inline these fallbacks? Is this introducing class selectors to the source?

**Comment by sotayamashita** [comment]
@jonathantneal Sorry I did not confirm my code perfectly. I will fix it

**Comment by sotayamashita** [comment]
@jonathantneal I fixed bug and here is [codepen link](http://codepen.io/sotayamashita/pen/NxBQvV).  I have a question. Scss has a  `variable-exists` function like https://github.com/10up/sanitize.css/blob/master/sanitize.scss#L62 but Less does not have so I implement this feature like below:

Scss:

``` css
small {
    font-size: if(variable-exists(small-font-size), $small-font-size, 75%); // All browsers
}
```

↓

Less

``` css
@small-font-size: 75%;

small {
    font-size: @small-font-size;  // All browsers
}

// If you want to override this value
// Please define @small-font-size: <Any value you want>
```

What do you think ? I asked this question in stackoverflow : http://stackoverflow.com/questions/35151189/how-do-i-check-if-a-variable-is-set-or-not-in-less-like-sasss-variable-exists

**Comment by jonathantneal** [comment]
I see, so Less variables can be [changed later on](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%2F%2F%20defaults%3A%5Cn%40font-size%3A%20%20%20100%25%3B%5Cn%40line-height%3A%201.5%3B%5Cn%5Cn%2F%2F%20styles%3A%5Cn.test%20%7B%5Cn%20%20%20font%3A%20%40font-size%2F%40line-height%3B%5Cn%7D%5Cn%5Cn%2F%2F%20user%2Fcustom%20overrides%20%28comment%2Funcomment%20to%20test%29%3A%5Cn%40font-size%3A%20%20%2033px%3B%5Cn%40line-height%3A%205.55%3B%22%7D), but they can’t be defined or given a fallback within the statement they are used, is that correct?

**Comment by jonathantneal** [comment]
Merged in 2c18eae. I did make a few corrections so it is completely in sync with the other files as much as can be possible.

**Pull request closed without merging**
