### PR TITLE
Don't override svg fill

### PR DESCRIPTION
**Pull request by davidmerrique**
Don't apply a fill if there's already a fill in the attribute.

### CODE REVIEW

**Comment by jonathantneal** [comment]
Resolves #165

**Comment by jonathantneal** [comment]
Thank you, @davidmerrique. I’ll see if I can get out a new release right now.

**Comment by davidmerrique** [comment]
@jonathantneal I appreciate it, thank you.

**Comment by jonathantneal** [comment]
Published in v8.0.0. 😄

**Comment by simevidas** [comment]
I use a class selector to set `fill`:

```css
.Icon {
    fill: var(--fill-color, currentColor);
}
```

After updating sanitize.css to the latest version (8.0.0), the new `svg:not([fill])` rule now overrides my own style because of its higher specificity.

Is this an issue? I added `!important` to my declaration for now.

**Comment by jonathantneal** [comment]
Maybe `html { fill: currentColor } svg { fill: inherit }`

**Comment by simevidas** [comment]
Unfortunately, that would still override the `<svg fill>` attribute:

https://jsbin.com/qexaqek/edit?html,css,output

However, it appears that [`fill` is already an inherited property](https://svgwg.org/svg2-draft/painting.html#SpecifyingFillPaint). If browsers correctly implement this definition, then setting `html { fill: currentColor }` should be enough.

**Pull request merged**
