### PR TITLE
fix(form-controls): remove background transparent

### LINKED ISSUE #133: Is background-color: transparent on form elements an issue?
When form elements are not styled by the web page, the browsers render them natively, i.e. they look like native controls on the user’s platform.

I’ve noticed that adding sanitize.css removes those native styles from my form elements. They appear unstyled and have ugly borders. If I understand correctly, this means that using sanitize.css **requires** the web page to style the form elements itself. 

foo

I’m wondering if it’s possible to use sanitize.css and still have form controls rendered by the browser as native controls. For now, I’ll use [my fork](https://github.com/simevidas/sanitize.css/commit/1e5c2b27f801f35c46fb2d5191decffb0426c05e) which doesn’t include the problematic line. It’s an ok hotfix, but I’m curious if there’s a better solution.

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #133 

Removes background transparent from the css and README.md.

### CODE REVIEW

**Comment by Dattaya** [comment]
@jonathantneal, the CI build has failed but I don't know if this PR is responsible, can you merge it?

**Comment by jonathantneal** [comment]
Merged! Linting fixed! Thanks, @levithomason !

**Comment by vicbell** [comment]
@jonathantneal  Is there any release plan?

**Comment by danieleleoni** [comment]
Hi, when could we expect a new release with this fix?

**Comment by blling** [comment]
Hi, when could we expect a new release with this fix?

**Pull request merged**
