### PR TITLE
Input height

### PR DESCRIPTION
**Pull request by brunorios1**
1) Is best practice to use line-height values without an unit.
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

2) Input min-height is using the $default-line-height value.
The problem is that line-height value can be unitless and normal, which are not valid values for min-height;

Also, line-height value can use percentage, that will cause vertical alignment issues for inputs.

This pull-request handles all possible valid values for line-height and fix input min-height accordingly.

Thanks!

### CODE REVIEW

**Comment by jonathantneal** [comment]
Nice work! Does `vertical-align` need to be assigned? I removed the universal `vertical-align: top`.

**Comment by brunorios1** [comment]
I will review the code.

**Comment by jonathantneal** [comment]
My apologies, I have a pending commit. It addresses only half of your request, as you’ve also accounted for percentage heights. I will fix and post my commit, and then update you shortly. I would greatly appreciate your review.

**Comment by jonathantneal** [comment]
Please review.

**Comment by brunorios1** [comment]
Hey @jonathantneal,

your commit looks good, but we still need to consider "normal", "inherit" and "initial" values for line-height:

```
[gulp-sass] argument `$number` of `unitless($number)` must be a number
Backtrace:
    node_modules/sanitize.css/sanitize.scss:12, in function `unitless`
    node_modules/sanitize.css/sanitize.scss:12, in function `if`
    node_modules/sanitize.css/sanitize.scss:12 on line 12 in /home/brunorios/www/moskit/node_modules/sanitize.css/sanitize.scss
```

Thanks!

**Comment by ungoldman** [comment]
@brunorios1 is this addressed by latest changes? would you be willing to rebase and for additional fixes?

**Comment by jonathantneal** [comment]
This will be handled by 2.0.0

**Pull request closed without merging**
