### PR TITLE
A bunch of smaller changes…

### PR DESCRIPTION
**Pull request by FabianBeiner**
Hi!

I just started a new project and used sanitize.css instead of normalize.css for the first time. So thanks for your work (again). :+1: 

This pull request contains a few smaller changes:
- I added the version to the “copyright comment”. This makes it much easier to check if you’re using the latest version in your project.
- I also added “1.0” to the CC0 license – because you never know if there will be a 2.0 out tomorrow which does something you don’t want.
- The monospace definition got doubled, if the user didn’t change the default of `$monospace-font-family`.
- I am, for example, most times using the font color as the selection color. And I actually see this quiet often. Anyway, to make sure the selected text will be readable in any case, I decided to use the invert() of the selected background color. Another idea would be to just use #000 or #FFF or something. Or – of course – ask the user for the text color, too.
- I updated the package.json and the gulp.js. It’s now using autoprefixer and postCSS. I took the versions from the README.
- I added “sans-serif” to an example in the README. Why? Image the browser would have Times as default font and “Open Sans” wouldn’t be available. This would mean a fall back to a serif font instead of _any_ sans-serif. (It’s just showing “best practice”, nothing fancy here…)

Yep, that’s it for now. :wave:

### CODE REVIEW

**Comment by jonathantneal** [comment]
You’ve separated your commits brilliantly. They are clean, readable commits that stray from doing too many things. Thank you.

Now, it’s hard to accept this commit as-is, because I’m unconvinced with some of your choices. May we dialog?

The monospace font family has [weird issues](http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/). After reading that, would you still want to remove the second monospace? If so, why? I think my choice was the least poisonous.

I really like how you’ve used `invert` to generate the text color of a selection. Would you mind if that invert value is the default value for something like a `$selection-color` variable?

I’m on the fence about Autoprefixer for Sanitize. On the one hand, I don’t want to repeat selectors, but on the other hand there are cases obvious where I’d only want to declare one property and let a machine figure out which properties I also meant. I love moving to the PostCSS ecosystem.

Which leads me to this — I’ve been thinking deeply about dropping Sass in exchange for in-spec CSS transpiled by PostCSS.
1. PostCSS has the tools to give us variables and nesting.
2. PostCSS can allow us to keep single line comments.
3. I prefer the way the CSS variables with fallbacks work.
4. I think that the syntax is probably more future-proof.

Finally, your copyright comment is right on, and I really appreciate that you moved the exports into its own commit. I can’t compliment this PR enough. What do you think of my ideas and opinions?

**Comment by FabianBeiner** [comment]
> After reading that, would you still want to remove the second monospace? If so, why? I think my choice was the last poisonous.

No. :scream:

> Would you mind if that invert value is the default value for something like a $selection-color variable?

Added this one. I didn’t do it in the first place because I thought I don’t want to fiddle with your variables. But then again, this is of course the better approach.

> I’m on the fence about Autoprefixer for Sanitize.

I get that. But I think for now it’s the best approach. At least until you switched to PostCSS.

> I’ve been thinking deeply about dropping Sass in exchange for in-spec CSS transpiled by PostCSS.

I get that. For now, I prefer SASS because I’m using it in a looooot of projects. And it’s super convenient to just use the .scss in my setup. Then again, I wouldn’t care to make it work. Question is: Do others? So it’s all up to you. :)

**Comment by FabianBeiner** [comment]
Oh, shoot! Now the “rename” got added too.

I added this one, because I was just working with the end result (the `.css` file) to test the monospace issue. :smile: I realized, that if you want to work with the export, it’s pretty hard because of the minifying. So removing `minifyCSS()` was a good solution for me. Then again, there might we people who just want to throw the `.css` file into their `<header>` and use it. For those, the “real” minified version should be the preferred one.

Any thoughts? :)

**Comment by jonathantneal** [comment]
Agreed on Autoprefixer. For now, it’s a win for users, and only a minor release, as there are new features but not breaking changes. Perhaps the next major release could have both the **cssnext** and **Sass** versions in the root.

Thanks again for this. Depending on what’s easier for you, would you clean up your commit history in this PR, or alternatively, reset your branch and recreate the individual changes so they’ll be clean? If not, I can try to do this late tonight.

**Comment by FabianBeiner** [comment]
So you want one commit with all changes? I can do this later. Should I bump the version to 2.0.1 or will you do that?

**Comment by jonathantneal** [comment]
I’d like a commit with one commit per change, so this would mean no revert commit, the text selection color variable and color invert would be one commit, etc.

**Comment by FabianBeiner** [comment]
Hehe, that's a new one for me. But yeah, I can do that. But it'll probably be tomorrow. Because later is now and I didn't have time today. ;)

**Pull request closed without merging**
