### PR TITLE
Also apply the `block-size` property to the `:root`

### PR DESCRIPTION
**Pull request by yuheiy**
In order to fill the viewport block, we need to apply `block-size` property not only to the `body` but also to the `:root`.

### CODE REVIEW

**Comment by jonathantneal** [comment]
@yuheiy, would you provide an example showing things not working with the current fix?

**Comment by yuheiy** [comment]
This is the situation where the current fix does not work:

https://codepen.io/yuheiy/pen/QWppXzg

I expect the following to be true:

https://codepen.io/yuheiy/pen/zYZZVyJ

**Comment by jonathantneal** [comment]
@yuheiy, this fix is good. I broke my own rule, and I had only tested in Safari. This is only solution I could find that worked in _all_ browsers.

```css
/* toggle this rule in Chrome, Edge, and Firefox. */
:where(html, body) {
	block-size: 100%;
	block-size: -webkit-available;
}
```

https://codepen.io/jonneal/pen/4a72bfdaac5ee71c070709da628e1db7

**Comment by yuheiy** [comment]
Oh, that's great. Should I discard this PR?

**Comment by jonathantneal** [comment]
If someone could test this solution, or my (not so recent) suggestion, I could add this back into sanitize.css. The solution I had in the HEAD, prior to v13, was failing for me, which is why I pulled it before the release.

**Pull request closed without merging**
